apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nazargora/test-hello-world.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: argocd.enabled
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
