{{- if .Values.argocd.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: presync-approval-job
  namespace: argocd
  labels:
    app: presync-approval
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: local-tmp
          hostPath:
            path: /tmp/presync
      containers:
        - name: wait-for-approval
          image: gora04/mini-deb:v1
          volumeMounts:
            - name: local-tmp
              mountPath: /tmp/presync
          env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-token-secret
                  key: SLACK_BOT_TOKEN
            - name: ARGOCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argocd-password
                  key: ARGOCD_PASSWORD
            - name: APP_NAME
              value: "my-test-app"
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "=========================="
              echo "PreSync Job: Using custom image with dependencies!"
              echo "=========================="

              source /opt/venv/bin/activate  

              echo "[INFO] Logging in to Argo CD server..."
              argocd login argocd-stone.demoapps.win \
                --username test \
                --password "$ARGOCD_PASSWORD" \
                --insecure \
                --grpc-web

              mkdir -p "/tmp/presync/$APP_NAME"

              SIGNAL_FILE="/tmp/presync/$APP_NAME/approval_signal"
              EMAILS_FILE="/tmp/presync/$APP_NAME/approved_emails"
              MSG_METADATA="/tmp/presync/$APP_NAME/msg_metadata"
              export SIGNAL_FILE EMAILS_FILE MSG_METADATA

              if [ -z "$MSG_METADATA" ]; then
                echo "[ERROR] MSG_METADATA environment variable is not set!"
                exit 1
              fi

              echo "[INFO] Generating DIFF..."
              DIFF=$(argocd app diff "$APP_NAME" --refresh --exit-code=false || true)
              DIFF_FILE="/tmp/presync/$APP_NAME/diff.txt"
              echo "$DIFF" > "$DIFF_FILE"
              echo "[INFO] Diff saved to $DIFF_FILE"

              # Python script to reorder Slack blocks: Approve/Reject first, then diff
              cat <<'EOF' > /tmp/post_to_slack.py
              import os
              import sys
              from slack_sdk import WebClient
              from slack_sdk.errors import SlackApiError

              SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
              APP_NAME = os.getenv("APP_NAME", "unknown-app")
              MSG_METADATA = os.getenv("MSG_METADATA")
              DIFF_FILE = f"/tmp/presync/{APP_NAME}/diff.txt"

              if not os.path.isfile(DIFF_FILE):
                  print(f"[ERROR] Diff file not found: {DIFF_FILE}", file=sys.stderr)
                  sys.exit(1)

              if not MSG_METADATA:
                  print("[ERROR] MSG_METADATA is not set!", file=sys.stderr)
                  sys.exit(1)

              channel_id = "C087P4N117X"  # Replace with your Slack channel ID

              client = WebClient(token=SLACK_BOT_TOKEN)

              # Read entire diff
              with open(DIFF_FILE, "r") as f:
                  diff_content = f.read()

              # Optional: Truncate the inline diff if it's large (Slack has block text limits)
              TRUNC_LIMIT = 3000
              truncated_diff = diff_content[:TRUNC_LIMIT]
              if len(diff_content) > TRUNC_LIMIT:
                  truncated_diff += "\n[... Diff truncated ...]"

              try:
                  # 1) Upload the full diff file to Slack
                  upload_response = client.files_upload_v2(
                      channel=channel_id,
                      file=DIFF_FILE,
                      title=f"Diff for {APP_NAME}",
                      filename=f"diff-{APP_NAME}.txt",
                      initial_comment=f"Diff file for {APP_NAME}"
                  )

                  files_list = upload_response.get("files", [])
                  if not files_list:
                      print("[ERROR] Slack upload returned no files.", file=sys.stderr)
                      sys.exit(1)

                  file_id = files_list[0]["id"]
                  # 2) Grab permalink so we can reference the full diff
                  file_info = client.files_info(file=file_id)
                  file_link = file_info["file"]["permalink"]

                  # 3) Post the interactive message
                  # The top section: Approve/Reject Buttons
                  # Then a second section with the truncated diff
                  response = client.chat_postMessage(
                      channel=channel_id,
                      text=f"Deployment pending approval for *{APP_NAME}*",
                      blocks=[
                          {
                              "type": "actions",
                              "elements": [
                                  {
                                      "type": "button",
                                      "text": {"type": "plain_text", "text": "Approve"},
                                      "value": "approve_value",
                                      "action_id": "approve_button"
                                  },
                                  {
                                      "type": "button",
                                      "text": {"type": "plain_text", "text": "Reject"},
                                      "value": "reject_value",
                                      "action_id": "reject_button"
                                  }
                              ]
                          },
                          {
                              "type": "section",
                              "text": {
                                  "type": "mrkdwn",
                                  "text": (
                                      f"*Diff (truncated)*:\n```{truncated_diff}```\n\n"
                                      f"Full diff file: <{file_link}|View Full Diff>"
                                  )
                              }
                          }
                      ]
                  )

                  posted_channel = response["channel"]
                  posted_ts = response["ts"]

                  # 4) Store channel + ts for updating later
                  with open(MSG_METADATA, "w") as f:
                      f.write(f"{posted_channel}||{posted_ts}")

                  print(f"[INFO] Slack message posted successfully. channel_id={posted_channel}, ts={posted_ts}")

              except SlackApiError as e:
                  print(f"[ERROR] Slack post failed: {e.response['error']}", file=sys.stderr)
                  sys.exit(1)
              EOF

              echo "[INFO] Posting to Slack..."
              python3 /tmp/post_to_slack.py

              echo "[INFO] Waiting for Slack approval/rejection..."
              TIMEOUT=100
              SECS=0
              while [ $SECS -lt $TIMEOUT ]; do
                if [ -f "$SIGNAL_FILE" ]; then
                  VAL=$(cat "$SIGNAL_FILE" | tr '[:upper:]' '[:lower:]')
                  if [ "$VAL" = "approve" ]; then
                    echo "[INFO] => APPROVED! Exiting 0 => ArgoCD continues."
                    exit 0
                  elif [ "$VAL" = "reject" ]; then
                    echo "[INFO] => REJECTED! Terminating the ArgoCD operation..."
                    argocd app terminate-op "$APP_NAME" --insecure --grpc-web
                    exit 1
                  else:
                    echo "[WARN] Unrecognized signal '$VAL'; ignoring..."
                  fi
                fi
                echo "[INFO] $(date) => Still waiting for Slack approval... ($SECS seconds elapsed)"
                sleep 5
                SECS=$((SECS+5))
              done

              echo "[INFO] TIMEOUT! No Slack response => Cancelling the ArgoCD operation..."
              argocd app terminate-op "$APP_NAME" --insecure --grpc-web

              cat <<'UPDATETIMEOUT' > /tmp/update_slack_timeout.py
              import os
              import sys
              from slack_sdk import WebClient
              from slack_sdk.errors import SlackApiError

              SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
              APP_NAME = os.getenv("APP_NAME", "unknown-app")
              MSG_METADATA = os.getenv("MSG_METADATA")

              if not MSG_METADATA:
                  print("[ERROR] MSG_METADATA is not set in the environment!", file=sys.stderr)
                  sys.exit(1)
              if not os.path.exists(MSG_METADATA):
                  print(f"[ERROR] Missing {MSG_METADATA} for Slack channel/ts", file=sys.stderr)
                  sys.exit(1)

              client = WebClient(token=SLACK_BOT_TOKEN)

              with open(MSG_METADATA, "r") as f:
                  line = f.read().strip()
              try:
                  channel_id, original_ts = line.split("||", 1)
              except ValueError:
                  print("[ERROR] Could not parse channel/ts from msg_metadata", file=sys.stderr)
                  sys.exit(1)

              try:
                  client.chat_update(
                      channel=channel_id,
                      ts=original_ts,
                      text=f"Deployment approval for *{APP_NAME}* has *timed out*. Cancelling...",
                      blocks=[]
                  )
                  print("[INFO] Timeout Slack message updated.")
              except SlackApiError as e:
                  print(f"[ERROR] {e.response['error']}", file=sys.stderr)
                  sys.exit(1)
              UPDATETIMEOUT

              python3 /tmp/update_slack_timeout.py

              echo "[INFO] Removing leftover files: /tmp/presync/$APP_NAME ..."
              rm -rf "/tmp/presync/$APP_NAME"

              echo "[INFO] Exiting with code 1 => Argo sees hook as failed."
              exit 1
{{- end }}







